# Generated by Django 5.1.7 on 2025-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('documento', models.IntegerField(verbose_name='N° de documento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(max_length=10, verbose_name='Horas')),
                ('servicio', models.CharField(max_length=100, null=True, verbose_name='Servicio')),
            ],
        ),
    ]
